<div id="footer" class="clearfix">
    <ul>
        <li><a href="index.html">首页</a> |</li>
        <li><a href="index2.html">客户</a> |</li>
        <li><a href="index2.html">产品</a> |</li>
        <li><a href="index2.html">产品销售</a> |</li>
        <li><a href="index2.html">核销单管理</a> |</li>
        <li><a href="index2.html">分票结算</a></li>
    </ul>
    <p>版权归作者所有  |  <a>网站使用意见反馈</a><span>公司网站1：</span><a href="http://www.hanyork.com" target="_blank" title="hanyork.com">hanyork.com</a><span>公司网站2：</span><a href="http://www.hanyorksports.com" target="_blank" title="hanyorksports.com">hanyorksports.com</a></p>
</div>