<div class="addNotice">
    <div class="options">
        <div class="selectShare">
            <select>
                <option>个人分享</option>
                <option>工作分享</option>
            </select>
        </div>
                <a href="javascript:void(0)" onclick="showPage('?who=addshare',550,400)"><span class="noticeadd"><img src="../../images/button/plus.png" width="14px" height="14px">新建</span></a>
        <a href="javascript:void(0)" onclick="listpost2pop('addshare',600,400)"><span class="noticeadd"><img src="../../images/button/pencil_edit.png" width="14px" height="14px">修改</span></a>
        <a href="javascript:void(0)" onclick="listpost2pop('deletecontent',550,450)"><span class="noticeadd"><img src="../../images/button/close_delete.png" width="14px" height="14px">删除</span></a>
        <a href="javascript:void(0)" onclick="listpost2pop('popview',700,500)"><span class="noticeadd"><img src="../../images/button/comment.png" width="14px" height="14px">查看</span></a>
    </div>
    <table class="more" tip="addshare">
        <tr>
            <th width="25%">创建时间</th>
            <th width="50%">标题</th>
        </tr>
        <tr>
            <td width="25%">2012-01-02 10:30:32</td>
            <td width="50%">数据单汇总通知数据单汇总通知数据单汇总通知数据单汇总通数据单汇总通知数据单汇总通知数据单汇总通知数据单汇总通</td>
        </tr>

        <tr>
            <td colspan="2" class="tablebottom">
                <span>当前显示 1-1条， 共1条</span> <span> <a><img src="../../images/button/top.png" width="18px" height="18px"></a> <a><img src="../../images/button/preview.png" width="18px" height="18px"></a> | 第 <input type="text" value=""> 页 共1页 | <a><img src="../../images/button/next.png" width="18px" height="18px"></a> <a><img src="../../images/button/end.png" width="18px" height="18px"></a></span>
            </td>
        </tr>

    </table>
</div>